spring:
    datasource:
        url: jdbc:mysql://localhost:3307/shadouyou?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    mail:
        host: smtp.qq.com
        username: 1061919896@qq.com
        password: nlwubmtjddlvbeef
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true
                        required: true
                    socketFactory:
                        class: javax.net.ssl.SSLSocketFactory
                        port: 465
server:
    port: 8181